Pickle_PKL:
    format_name: PKL
    module_name: Pickle
    object_type_info:
        - builtins
        - object
    priority: 0

Json_JSON:
    format_name: JSON
    module_name: Json
    object_type_info:
        - builtins
        - dict
    priority: 10
